version: "3.4"
services:
  node:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: toantnweb/reddit-node
    restart: always
    environment:
      - PORT=3030
    volumes:
      - .:/home/app
    tty: true
    ports:
      - "3030:3030"
    entrypoint:
      - ./entrypoint.sh
    working_dir: /home/app
    depends_on:
      - mysql

  mysql:
    restart: always
    image: mysql:5.7
    volumes:
      - database:/var/lib/mysql
    ports:
      - "3306:3306"
    expose:
      - 3306
    environment:
      MYSQL_DATABASE: reddit_db
      MYSQL_ROOT_PASSWORD: 123456

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080

volumes:
  database:
    driver: local
    name: red-snack-db
